name: Build & Push Admin Hub

on:
  push:
    paths:
      - "./banking-admin-hub-main/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Admin Hub
        uses: docker/build-push-action@v5
        with:
          context: ./banking-admin-hub-main/
          push: true
          tags: bridget1004/mini-banking-admin-hub:latest
